import { Duration, Pitch } from "src/types";
import { GameStore } from "./types";

export const mockStore: GameStore = {
  addNote: () => {},
  answerStatuses: [],
  availableDurations: [],
  availablePitches: [],
  bpm: 0,
  checkGuesses: () => {},
  correctNotes: [],
  durationsGuessed: new Set([]),
  guessedEverythingCorrect: true,
  guesses: [],
  incorrectDurationsArrays: [],
  incorrectPitchesArrays: [],
  incrementGuessDuration: (index: number, increment: number) => {},
  incrementGuessPitch: (index: number, increment: number) => {},
  incrementTurn: () => {},
  overrideBPM: (bpm: number) => {},
  pitchesGuessed: new Set([]),
  removeNote: () => {},
  selectedNoteIndex: 0,
  setSelectedGuessDuration: (duration: Duration) => {},
  setSelectedGuessPitch: (pitch: Pitch) => {},
  setSelectedNoteIndex: (selectedNoteIndex: number) => {},
  showCongrats: false,
  showInstructions: false,
  showOutput: false,
  showSupportUs: false,
  switchIsRest: () => {},
  switchIsStaccato: () => {},
  toggleCongrats: () => {},
  toggleInstructions: () => {},
  toggleOutputModal: () => {},
  toggleSupportUs: () => {},
  turn: 0,
  wrongSpotDurations: new Set([]),
  wrongSpotPitches: new Set([]),
};
