import { GameSong, TimeSignature } from "src/types";

const testSong: GameSong = {
  bpm: 113,
  timeSignature: TimeSignature.FOURFOUR,
  readyForProduction: true,
  notes: [
    { pitch: "C5", durations: [ "8n"] },
    { pitch: "C5", durations: [ "8n"] },
    { pitch: "C5", durations: [ "8n"] },
    { pitch: "C5", durations: [ "8n"] },
    { pitch: "C5", durations: [ "8n"] },
    { pitch: "C5", durations: [ "8n"] },
    { pitch: "C5", durations: [ "8n"] },
    { pitch: "C5", durations: [ "8n"] },
  ],
  name: "Midly Opus No. " + Math.random().toString()
};

export const gameSongs: Array<GameSong> = [
  testSong,
];


export const gameSongsString = `[
  simpsonsTheme,
  imperialMarch,
  hedwigsTheme,
  thomasTheTankEngine,
  theMandalorian,
  marioBrosMainTheme,
  concerningHobbits,
  aGrandDayOut,
  missionImpossible,
  sunflower,
  theRaidersMarch,
  theChain,
  leFestin,
  standByMe,
  spiritedAwayReprise,
  tetris,
  marriedLife,
  tinyDancer,
  smokeOnTheWater,
  gourmetRace,
  zeldaMainTheme,
  chameleon,
  sevenNationArmy,
  carryOnMyWaywardSon,
  tossACoinToYourWitcher,
  heyJude,
  theLonelyShepherd,
  flyMeToTheMoon,
  oneSummersDay,
  stayinAliveIntro,
  schindlersList,
  furElise,
  avatarLegendOfAang,
  cityOfStars,
  strangerThings,
  dancingInTheMoonlight,
  battleOfTheHeroes,
  theTimeIsNow,
  september,
  cantinaBand,
  blindingLights,
  theGloryDays,
  gavityFallsTheme,
  underTheMilkyWay,
  pokemonGottaCatchEmAll,
  goodMornin,
  uptownFunkIntro,
  miiChannel,
  punchOut,
  vertigo,
  spidermanSpiderman,
  shapeOfYouIntro,
  insideTheCastleWalls,
  myHeartWillGoOnIntro,
  monstersInc,
  delfinoPlaze,
  letEmIn,
  stayinAliveChorus,
  lifesIncredibleAgain,
  canYouFeelTheLoveTonight,
  theOffice,
  bobombBattlefield,
  loveStoryIntro,
  gavityFallsTheme,
];


`